In [7]:
from sidechainnet.structure.build_info import ATOM_MAP_HEAVY
from sidechainnet.utils.sequence import ONE_TO_THREE_LETTER_MAP, THREE_TO_ONE_LETTER_MAP
from openfold.np.residue_constants import restype_name_to_atom14_names

import torch

In [ ]:
def get_openfold_to_sidechainnet_mapping():
    openfold_idx_to_scn_idx = {}
    openfold_name_to_openfold_idx = {}
    for resname, atom_names in restype_name_to_atom14_names.items():
        openfold_name_to_openfold_idx[resname] = {atom_name: i for i, atom_name in enumerate(atom_names) if atom_name}

    scn_name_to_scn_idx = {}
    for resid, atom_names in ATOM_MAP_HEAVY.items():
        # atom_names = ['N', 'CA', 'C', 'O'] + [v for v in values['atom-names'] if not v.startswith('H')]
        resname = ONE_TO_THREE_LETTER_MAP[resid]
        scn_name_to_scn_idx[resname] = {atom_name: i for i, atom_name in enumerate(atom_names) if atom_name != "PAD"}
    
    openfold_idx_to_scn_idx = {}
    # Now, compare the two dictionaries to make note of where the differences are
    for (resname, scn_atomnames) in scn_name_to_scn_idx.items():
        rescode = THREE_TO_ONE_LETTER_MAP[resname]
        openfold_idx_to_scn_idx[rescode] = {}
        for scn_atomname, scn_idx in scn_atomnames.items():
            try:
                openfold_idx = openfold_name_to_openfold_idx[resname][scn_atomname]
            except KeyError:
                # openfold_idx = scn_atomname
                # don't add this atom to the dictionary
                continue
            openfold_idx_to_scn_idx[rescode][openfold_idx] = scn_idx
        openfold_idx_to_scn_idx[rescode] = (torch.tensor(list(openfold_idx_to_scn_idx[rescode].keys())), 
                                            torch.tensor(list(openfold_idx_to_scn_idx[rescode].values())))
    
    return openfold_idx_to_scn_idx

In [2]:
openfold_idx_to_scn_idx = {}
openfold_name_to_openfold_idx = {}
for resname, atom_names in restype_name_to_atom14_names.items():
    openfold_name_to_openfold_idx[resname] = {atom_name: i for i, atom_name in enumerate(atom_names) if atom_name}


In [8]:
scn_name_to_scn_idx = {}
for resid, atom_names in ATOM_MAP_HEAVY.items():
    # atom_names = ['N', 'CA', 'C', 'O'] + [v for v in values['atom-names'] if not v.startswith('H')]
    resname = ONE_TO_THREE_LETTER_MAP[resid]
    scn_name_to_scn_idx[resname] = {atom_name: i for i, atom_name in enumerate(atom_names) if atom_name != "PAD"}

In [9]:
openfold_name_to_openfold_idx

{'ALA': {'N': 0, 'CA': 1, 'C': 2, 'O': 3, 'CB': 4},
 'ARG': {'N': 0,
  'CA': 1,
  'C': 2,
  'O': 3,
  'CB': 4,
  'CG': 5,
  'CD': 6,
  'NE': 7,
  'CZ': 8,
  'NH1': 9,
  'NH2': 10},
 'ASN': {'N': 0,
  'CA': 1,
  'C': 2,
  'O': 3,
  'CB': 4,
  'CG': 5,
  'OD1': 6,
  'ND2': 7},
 'ASP': {'N': 0,
  'CA': 1,
  'C': 2,
  'O': 3,
  'CB': 4,
  'CG': 5,
  'OD1': 6,
  'OD2': 7},
 'CYS': {'N': 0, 'CA': 1, 'C': 2, 'O': 3, 'CB': 4, 'SG': 5},
 'GLN': {'N': 0,
  'CA': 1,
  'C': 2,
  'O': 3,
  'CB': 4,
  'CG': 5,
  'CD': 6,
  'OE1': 7,
  'NE2': 8},
 'GLU': {'N': 0,
  'CA': 1,
  'C': 2,
  'O': 3,
  'CB': 4,
  'CG': 5,
  'CD': 6,
  'OE1': 7,
  'OE2': 8},
 'GLY': {'N': 0, 'CA': 1, 'C': 2, 'O': 3},
 'HIS': {'N': 0,
  'CA': 1,
  'C': 2,
  'O': 3,
  'CB': 4,
  'CG': 5,
  'ND1': 6,
  'CD2': 7,
  'CE1': 8,
  'NE2': 9},
 'ILE': {'N': 0,
  'CA': 1,
  'C': 2,
  'O': 3,
  'CB': 4,
  'CG1': 5,
  'CG2': 6,
  'CD1': 7},
 'LEU': {'N': 0,
  'CA': 1,
  'C': 2,
  'O': 3,
  'CB': 4,
  'CG': 5,
  'CD1': 6,
  'CD2': 7},
 'L

In [10]:
scn_name_to_scn_idx

{'ALA': {'N': 0, 'CA': 1, 'C': 2, 'O': 3, 'OXT': 4, 'CB': 5},
 'ARG': {'N': 0,
  'CA': 1,
  'C': 2,
  'O': 3,
  'OXT': 4,
  'CB': 5,
  'CG': 6,
  'CD': 7,
  'NE': 8,
  'CZ': 9,
  'NH1': 10,
  'NH2': 11},
 'ASN': {'N': 0,
  'CA': 1,
  'C': 2,
  'O': 3,
  'OXT': 4,
  'CB': 5,
  'CG': 6,
  'OD1': 7,
  'ND2': 8},
 'ASP': {'N': 0,
  'CA': 1,
  'C': 2,
  'O': 3,
  'OXT': 4,
  'CB': 5,
  'CG': 6,
  'OD1': 7,
  'OD2': 8},
 'CYS': {'N': 0, 'CA': 1, 'C': 2, 'O': 3, 'OXT': 4, 'CB': 5, 'SG': 6},
 'GLN': {'N': 0,
  'CA': 1,
  'C': 2,
  'O': 3,
  'OXT': 4,
  'CB': 5,
  'CG': 6,
  'CD': 7,
  'OE1': 8,
  'NE2': 9},
 'GLU': {'N': 0,
  'CA': 1,
  'C': 2,
  'O': 3,
  'OXT': 4,
  'CB': 5,
  'CG': 6,
  'CD': 7,
  'OE1': 8,
  'OE2': 9},
 'GLY': {'N': 0, 'CA': 1, 'C': 2, 'O': 3, 'OXT': 4},
 'HIS': {'N': 0,
  'CA': 1,
  'C': 2,
  'O': 3,
  'OXT': 4,
  'CB': 5,
  'CG': 6,
  'ND1': 7,
  'CE1': 8,
  'NE2': 9,
  'CD2': 10},
 'ILE': {'N': 0,
  'CA': 1,
  'C': 2,
  'O': 3,
  'OXT': 4,
  'CB': 5,
  'CG1': 6,
  'CD1'

In [13]:
openfold_idx_to_scn_idx = {}
# Now, compare the two dictionaries to make note of where the differences are
for (resname, scn_atomnames) in scn_name_to_scn_idx.items():
    rescode = THREE_TO_ONE_LETTER_MAP[resname]
    openfold_idx_to_scn_idx[rescode] = {}
    for scn_atomname, scn_idx in scn_atomnames.items():
        try:
            openfold_idx = openfold_name_to_openfold_idx[resname][scn_atomname]
        except KeyError:
            # openfold_idx = scn_atomname
            # don't add this atom to the dictionary
            continue
        openfold_idx_to_scn_idx[rescode][openfold_idx] = scn_idx
    openfold_idx_to_scn_idx[rescode] = (torch.tensor(list(openfold_idx_to_scn_idx[rescode].keys())), 
                                        torch.tensor(list(openfold_idx_to_scn_idx[rescode].values())))

In [14]:
openfold_idx_to_scn_idx

{'A': (tensor([0, 1, 2, 3, 4]), tensor([0, 1, 2, 3, 5])),
 'R': (tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
  tensor([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 10, 11])),
 'N': (tensor([0, 1, 2, 3, 4, 5, 6, 7]), tensor([0, 1, 2, 3, 5, 6, 7, 8])),
 'D': (tensor([0, 1, 2, 3, 4, 5, 6, 7]), tensor([0, 1, 2, 3, 5, 6, 7, 8])),
 'C': (tensor([0, 1, 2, 3, 4, 5]), tensor([0, 1, 2, 3, 5, 6])),
 'Q': (tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]),
  tensor([0, 1, 2, 3, 5, 6, 7, 8, 9])),
 'E': (tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]),
  tensor([0, 1, 2, 3, 5, 6, 7, 8, 9])),
 'G': (tensor([0, 1, 2, 3]), tensor([0, 1, 2, 3])),
 'H': (tensor([0, 1, 2, 3, 4, 5, 6, 8, 9, 7]),
  tensor([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 10])),
 'I': (tensor([0, 1, 2, 3, 4, 5, 7, 6]), tensor([0, 1, 2, 3, 5, 6, 7, 8])),
 'L': (tensor([0, 1, 2, 3, 4, 5, 6, 7]), tensor([0, 1, 2, 3, 5, 6, 7, 8])),
 'K': (tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]),
  tensor([0, 1, 2, 3, 5, 6, 7, 8, 9])),
 'M': (tensor([0, 1, 2, 3, 4, 5, 6, 7]), tensor([0, 

In [22]:
import torch

fake_protein = torch.randn(30, 14, 3)
new_protein = torch.zeros(30, 15, 3) * torch.nan

In [23]:
ala_select = torch.tensor([0, 1, 2, 3, 4])
ala_target = torch.tensor([0, 1, 2, 3, 5])
ala_select, ala_target

(tensor([0, 1, 2, 3, 4]), tensor([0, 1, 2, 3, 5]))

In [4]:
fake_protein[0][ala_select]

tensor([[ 0.6511, -1.4065, -0.3671],
        [ 0.2174,  0.0221, -0.0380],
        [-0.3844,  1.6537, -0.0294],
        [ 0.0114,  0.2788, -0.4352],
        [-1.1242,  1.2282, -0.0454]])

In [10]:
new_protein[0][ala_target]

tensor([[nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan]])

In [11]:
new_protein[0][ala_target] = fake_protein[0][ala_select]
new_protein[0]

tensor([[ 0.5473, -0.6941,  1.6661],
        [ 0.7602, -0.1650, -0.6104],
        [-1.6638,  0.1101, -0.2453],
        [ 0.0262,  1.5561, -0.4287],
        [    nan,     nan,     nan],
        [ 0.4177,  0.9510,  0.8083],
        [    nan,     nan,     nan],
        [    nan,     nan,     nan],
        [    nan,     nan,     nan],
        [    nan,     nan,     nan],
        [    nan,     nan,     nan],
        [    nan,     nan,     nan],
        [    nan,     nan,     nan],
        [    nan,     nan,     nan],
        [    nan,     nan,     nan]])