In [13]:
import sidechainnet as scn
import numpy as np

In [2]:
d = scn.load('debug', scn_dataset=True)

SidechainNet('debug', 30) was not found in {scn_dir}.


Downloaded SidechainNet to ./sidechainnet_data/sidechainnet_debug.pkl.
SidechainNet was loaded from ./sidechainnet_data/sidechainnet_debug.pkl.


In [ ]:
def gdt_ts(true, pred):
    """Compute GDT_TS between true (nan-padded) and predicted coordinate tensors.

    Args:
        true (tensor): True atomic coordinates, must be padded with nans.
        pred (tensor): Predicted atomic coordinates.

    Returns:
        gdt_ts: Value of GDT_TS.
    """
    thresholds = np.array([1, 2, 4, 8])
    transformation = pr.calcTransformation(pred, true)
    pred_aligned = transformation.apply(pred)
    
    
    

In [4]:
d[0].coords

array([[  9.192,  64.268,   3.337],
       [ 10.005,  64.754,   2.182],
       [  9.98 ,  63.678,   1.068],
       [  9.422,  62.601,   1.267],
       [ 11.428,  65.07 ,   2.687],
       [ 12.34 ,  65.863,   1.745],
       [ 12.078,  66.246,   0.445],
       [ 13.199,  66.816,  -0.122],
       [ 14.206,  66.829,   0.806],
       [ 15.516,  67.304,   0.703],
       [ 16.317,  67.196,   1.812],
       [ 15.844,  66.631,   3.013],
       [ 14.545,  66.157,   3.118],
       [ 13.701,  66.25 ,   2.   ],
       [ 10.498,  63.999,  -0.119],
       [ 10.527,  63.054,  -1.247],
       [ 11.923,  62.867,  -1.876],
       [ 12.959,  63.115,  -1.248],
       [  9.56 ,  63.511,  -2.347],
       [ 10.053,  64.644,  -3.26 ],
       [  9.235,  64.688,  -4.54 ],
       [ 10.025,  65.976,  -2.533],
       [    nan,     nan,     nan],
       [    nan,     nan,     nan],
       [    nan,     nan,     nan],
       [    nan,     nan,     nan],
       [    nan,     nan,     nan],
       [    nan,     nan,   

In [22]:
c1 = d[0].coords.copy()[0:3, :]

In [23]:
c2 = c1.copy()

In [24]:
c1 = torch.tensor(c1)
c2 = torch.tensor(c2)

In [25]:
c1[0,:] -= .5

In [26]:
c1, c2

(tensor([[ 8.6920, 63.7680,  2.8370],
         [10.0050, 64.7540,  2.1820],
         [ 9.9800, 63.6780,  1.0680]], dtype=torch.float64),
 tensor([[ 9.1920, 64.2680,  3.3370],
         [10.0050, 64.7540,  2.1820],
         [ 9.9800, 63.6780,  1.0680]], dtype=torch.float64))

In [27]:
import torch

In [29]:
torch.norm(c1-c2, dim=-1)

tensor([0.8660, 0.0000, 0.0000], dtype=torch.float64)