In [1]:
import sidechainnet as scn

In [2]:
d = scn.load(local_scn_path='/home/jok120/scn220905/sidechainnet_debug12.pkl')

SidechainNet was loaded from /home/jok120/scn220905/sidechainnet_debug12.pkl.


In [3]:
d[0]

SCNProtein(10#4USL_2_D, len=6, missing=0, split='valid-10')

In [4]:
d[-1].to_3Dmol()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [5]:
d = scn.load(local_scn_path='/home/jok120/scn220905/sidechainnet_debug12.pkl', with_pytorch='dataloaders')

SidechainNet was loaded from /home/jok120/scn220905/sidechainnet_debug12.pkl.
Approximating 5600 residues/batch.


In [6]:
for batch in d['train']:
    print(batch.angles)
    break

tensor([[[    nan, -0.0078, -3.1250,  ...,     nan,     nan,     nan],
         [-1.6788, -0.4438,  3.1173,  ...,     nan,     nan,     nan],
         [-1.3267, -0.5606, -3.1353,  ..., -0.7465,     nan,     nan],
         ...,
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan]],

        [[    nan, -0.2771,  3.0623,  ...,     nan,     nan,     nan],
         [-1.8183, -0.0630, -3.0536,  ...,     nan,     nan,     nan],
         [-2.5086,  2.7782,  3.0872,  ...,     nan,     nan,     nan],
         ...,
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan]],

        [[    nan, -3.1405,  3.1019,  ...,     nan,     nan,     nan],
         [-2.7158,  2.7652,  3.1200,  ...,   

In [7]:
batch.angles.shape

torch.Size([10, 158, 12])

In [8]:
batch.seqs[0].shape

torch.Size([158, 20])

In [9]:
batch.seqs[0][-2]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
batch.seqs_int[0]

tensor([ 0,  9,  3,  3, 13, 14,  5, 12,  9, 12,  9, 11,  8, 16,  9,  4,  9,  5,
        19,  0,  4,  9,  9, 16, 10,  0, 16, 16, 15,  2,  8,  9,  0, 15, 14, 15,
         8,  9, 12,  2,  5, 12, 16,  5, 15, 15,  3,  3,  3,  3,  3,  4,  9,  3,
         7, 12, 12,  4, 11,  8, 13, 19, 16,  3, 15, 13,  9, 14,  0,  5,  0,  5,
        19,  7,  9,  3,  2,  4, 11,  3,  0, 13,  1, 11, 16,  0, 19, 13,  1,  9,
         9,  7,  0,  2, 13,  6,  1, 14, 16, 14,  8, 19,  4,  9,  1,  9,  0, 15,
         5,  7, 12,  1, 17, 15,  6, 17, 18, 17,  6,  2, 15,  1,  6,  0, 11, 13,
         9, 13, 11, 19, 14, 11, 19,  9,  9, 12,  0,  5, 19, 15,  9,  3,  3, 13,
        14,  7,  9,  2, 18, 13, 12, 14,  3, 20, 20, 20, 20, 20])

In [11]:
batch.masks[-1]

tensor([1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [13]:
batch.coords[0]

tensor([[[42.6010, 30.5990,  9.5920],
         [43.4130, 30.1160, 10.7460],
         [43.3410, 31.1080, 11.8990],
         ...,
         [    nan,     nan,     nan],
         [    nan,     nan,     nan],
         [    nan,     nan,     nan]],

        [[42.6060, 32.1980, 11.6920],
         [42.4690, 33.2420, 12.7100],
         [41.2100, 33.1400, 13.5920],
         ...,
         [    nan,     nan,     nan],
         [    nan,     nan,     nan],
         [    nan,     nan,     nan]],

        [[40.1500, 32.5120, 13.0800],
         [38.9080, 32.3330, 13.8500],
         [39.1530, 31.2120, 14.8670],
         ...,
         [    nan,     nan,     nan],
         [    nan,     nan,     nan],
         [    nan,     nan,     nan]],

        ...,

        [[    nan,     nan,     nan],
         [    nan,     nan,     nan],
         [    nan,     nan,     nan],
         ...,
         [    nan,     nan,     nan],
         [    nan,     nan,     nan],
         [    nan,     nan,     nan]],

        [[